apiVersion: apps/v1
kind: Deployment
metadata:
  name: qm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qm
  template:
    metadata:
      labels:
        app: qm
    spec:
      containers:
      - image: okteto.dev/qm:latest
        name: qm
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "beaaf6ae-ba3e-4388-82d4-13fd185aea69"
        - name: Vless_Path
          value: "/vl555"
        - name: Vmess_UUID
          value: "beaaf6ae-ba3e-4388-82d4-13fd185aea69"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
